# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weibo', '0012_auto_20160503_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=b'static/%Y/%m/%d'),
        ),
    ]
